### ISSUE TITLE
lost-waffle height collapsing when changing fraction in responsive

### ISSUE THREAD

**Issue by cre8websolutions** [peterramsing/lost#183]
The height of my `lost-waffle` items collapses when the fraction changes with responsive media queries.

```
.lost-grid {
	lost-utility: edit;
}

.lost-grid .card {
	lost-waffle: 1/4;
	height: 200px;
	
	div {
		lost-waffle: 1/2;

		div {
			lost-waffle: 1/2;
		}
	}

	@media (max-width: $screen-sm-max) {
		lost-waffle: 1/2;   // height gets overwritten
	}

	@media (max-width: $screen-xs-max) {
		lost-waffle: 1/1;   // height gets overwritten
	}
}
```

Replacing `lost-waffle` with `lost-column` inside the media queries maintains the height, but obviously loses the waffle bottom gutters functionality.

**Comment by cre8websolutions** [comment]
This can be closed, as I obviously need to set the height again after using `lost-waffle`, or use `!important` on the height.

**Comment by peterramsing** [comment]
@cre8websolutions Could you elaborate a bit more on this? I don't like to hear that a solution is to put `!important` on a rule.

**Comment by corysimmons** [comment]
lol - that's a lot of nested waffle grids. :^)

**Comment by ghost** [comment]
@peterramsing The `height` set on `.lost-grid .card` gets overwritten by the `lost-waffle` media query rules, when they take effect. `lost-waffle` affects the `height` property.
The need of `!important` in this situation is indeed a bit disappointing.

@corysimmons Just a little example, as I was following Laracasts' example. :)

**Comment by peterramsing** [comment]
@cre8websolutions I'll look into this a bit more. Any need of `!important` needs to be addressed, I feel.

**Comment by corysimmons** [comment]
Is the complaint that `height: 200px` is getting overridden? I'd expect it to and don't think this is a problem of Lost. Why use waffle if you're setting a custom height? The entire purpose of waffle is to set a height alongside a width. :^)

**Comment by elgandoz** [comment]
Hi guys. This is old, but I recently ran in the same issue, using a "card" component with waffle.
The height gets overridden, we could trick it using !important, max/min-width or line-height, but it will require an edit of the original component anyway. This could be annoying, especially if such component has few modifier classes, or if it comes from some package.
 
@corysimmons, I know this beats the purpose of waffle, but the main reason why I would still use it is because it correctly removes the bottom margin from the elements of the last row, and lost-column doesn't do it. 
I've been unproperly using it with success, without setting the height of the wrapper (it doesn't resolve the %, and it works like an height: auto). This is also the way it works in the demo (no height set, with items owerflowing nicely).

I was thinking, we could add a parameter to simply omit the height calculation, similar to 'float-right' in syntax:
`lost-waffle: 1/3 no-height;` or similar. In this way it would cover many more cases, and behaving better than lost-column.

@peterramsing Would it be ok to open a feature request? I never wrote postcss modules, but i could try with this one.
