### ISSUE TITLE
enable/disable initialization with a optional parameter

### ISSUE THREAD

**Issue by microcipcip** [peterramsing/lost#188]
Is it possible to disable lost column initialization? Sorry if I reopen this issue...see the [previous issue here](https://github.com/peterramsing/lost/issues/19#issuecomment-156059742)

**Comment by peterramsing** [comment]
It's certainly possible. I'm working on a feature roadmap and per #194 I think that ensuring that the code that Lost compiles to is as clean and doesn't duplicate a lot of code is important. Hopefully in the week I'll have some milestones laid out to implement some of this.

**Comment by peterramsing** [comment]
I'm going to keep this in mind but I don't think this is quite on the roadmap. LostGrid is more towards "on the fly" grids where you're applying the grid from the CSS. If you're wanting to do something like this I would recommend simply taking the outputted CSS and tailoring it within your CSS instead of relying on LostGrid to output it for you.

Let me know if I'm misunderstanding what you're looking for. Thanks!
