### ISSUE TITLE
lost-align issue

### ISSUE THREAD

**Issue by eybarta** [peterramsing/lost#233]
Thx for all your work, very refreshing using this grid and thx Peter for maintaining!

I'm not sure if I'm doing something wrong.. but using `lost-align` on a parent seems to give the `justify-content` and `align-items` properties to the children instead of the parent resulting in incorrect behavior.. I looked @ lost/lib/lost-align.js and it seems the conditional styles are always given to '  > \* ',
am I misunderstanding something or is this a bug?

**Comment by peterramsing** [comment]
@eybarta I might be misunderstanding this but it looks to be this works as expected. `lost-align` is intended to align the child elements. See here: [lost-align](https://github.com/peterramsing/lost#lost-align)

> Align nested elements. Apply this to a parent container.

Please let me know if this I'm not understanding this correctly. Maybe some of the code you're working with? Thanks!

**Comment by corysimmons** [comment]
Crap, I think @eybarta is right. `justify-content` and `align-items` should be applied to the parent container instead of `> *`.

`lost-align` is broken when used with global flexbox or the `flex` param.

**Comment by peterramsing** [comment]
Will look into this tonight.

**Comment by adrian2x** [comment]
I just noticed this too. I thing @eybarta is right too. Unlike the position-based alignment, the flex alignment properties should be applied on the container element, because they specify how a flex element arranges its items. The way that it is implemented right now, it will apply these properties (`justify-content` and `align-items`) to the actual children, which will make them in turn flex containers, according to the spec.
PR -> https://github.com/peterramsing/lost/pull/236

**Comment by adrianca** [comment]
Made a PR for this -> https://github.com/peterramsing/lost/pull/235

**Comment by corysimmons** [comment]
:tada:

**Comment by eybarta** [comment]
glad this is being addressed
thanks guys :+1:

**Comment by aguilera51284** [comment]
i have the same problem here :)!

**Comment by peterramsing** [comment]
Fixed here: https://github.com/peterramsing/lost/pull/339

You'll see this in the beta version soon and in LostGrid v8. 👍
