### ISSUE TITLE
lost-center left align

### ISSUE THREAD

**Issue by pixelize** [peterramsing/lost#269]
Hey guys,

I'm working on an ipad app. I need the lost center container to be aligned on the left side all the time (that mean without the margin-left: auto & margin-right: auto);

http://codepen.io/Pixelize/pen/eZdoBm

Is there any options for that please ?

Thanks in advance

**Comment by peterramsing** [comment]
@pixelize Are you meaning above the menu?

**Comment by pixelize** [comment]
No I mean, I want to container to be aligned on the left side rather than centered.
I did a dirty trick to overwrite the rules in the css which is working, but I was wondering if there wasn't an option for that ?

Thanks for the details Peter !

![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/2931627/13921889/59cd8354-ef7a-11e5-9f2a-282de9f8c926.gif)

**Comment by canvural** [comment]
You don't have to use `lost-center`. Its just for centering things.

**Comment by peterramsing** [comment]
@pixelize Like @canvural said: that's not necessarily what `lost-center` is used for. However, is this because you have media queries that have it "lost-centered" on mobile and thus it is being centered on the tablet viewport? Is that the issue?

Hopefully, I'm not totally missing what you're meaning. Sorry for the continued questions instead of solid answers.

**Comment by pixelize** [comment]
Thanks for taking on your time for helping me out Peter.

Alright so you just use regular CSS rules ?
I was thinking there was a mixin in LostGrid for setting max-width and padding without centering ;)

```
.wrap {
  max-width: 1024px;
  padding: 0 30px;
}
```

**Comment by peterramsing** [comment]
@pixelize When in doubt use regular CSS. LostGrid is extremely powerful at creating grids but it also will try to avoid catching every edge case because that just leads to unmaintainable code later causing many typical use cases to be more difficult.

Since taking over LostGrid several months ago this has been my goal. If you feel that this use case might be useful for many others then we could discuss it being an added feature.

**Comment by peterramsing** [comment]
This issue is getting a bit stale. If you'd like to bring this issue back up please feel free to reach out.
