### ISSUE TITLE
Incorrect column widths

### ISSUE THREAD

**Issue by jamielaughton** [peterramsing/lost#373]
*For support questions you might try tweeting me [@lostgrid](https://twitter.com/lostgrid) first.*

*If this is about the documentation site please submit issues for that on the site's repo: [github.com/lostgrid/lostgrid-site](https://github.com/lostgrid/lostgrid-site/issues/new).*

-----

**Is this a feature request or a bug report?**
Bug report

**What is the current behavior?**

When implementing 'lost-row: 1/2' on the child of a 1900px wrapper the div width returns:

width: calc(99.9% * 1/2 - (30px - 30px * 1/2)) ; 

Which = 934.05px not 950px which is half of the wrapper width, as you'd expect.

**What is the desired behavior?**
A column of 1/2 to be half of the wrapper width

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
Newest

**Comment by steve-holland** [comment]
@devnsc - Are you taking into account the gutter? 

By the looks of things you've got a gutter of 30px. So what you will find is that as you've got two columns the gutter will be divided by two and subtracted from the column widths. That way it all fits nicely into your container.

**Comment by steve-holland** [comment]
@devnsc - Are you still having a problem with this, or shall I go ahead and close the issue?

**Comment by peterramsing** [comment]
@devnsc It sounds like this is expected behavior. Feel free to comment back if we're missing something but I think what you're looking for can be done by specifying a custom gutter.

I also think you're meaning `lost-column`, not row? Could you confirm that?

Example: `lost-column: 1/2 2 0;` which will then set your gutter to be 0px wide.
http://lostgrid.org/docs.html#lost-column

...maybe I'm totally misunderstanding this with the `lost-row` vs `lost-column` so let us know and we can re-open and keep talking. 👍
