### ISSUE TITLE
small feature request: space 

### ISSUE THREAD

**Issue by diogoweb2** [peterramsing/lost#388]
**Is this a feature request or a bug report?**
Feature request

**What is the current behavior?**
IDEs extentions to format code like  https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-stylefmt adds space for lost operations, like: 
lost-column: 1 / 3 

I spent hours to find out the problem because webpack compiles fine and lostgrid kind of works. (it transforms the css but completely wrong)

**What is the desired behavior?**

Ideally space between operations would work but if this is not possible, I'd prefer to see an error msg when I compile. 

**What's the motivation or use-case behind changing the behavior?**
Very hard to find out the issue when IDEs automatically format code.

**Anything else?**
Great job!

**Comment by peterramsing** [comment]
My initial reaction is to try to fix the error handling ( #180 ). It's not a glamorous feature but something that would certainly help out.

I'm not sure how I feel about the `1 / 3` syntax...it feels like having errors would be better than fixing that right now because if we fix that we're only fixing one of the many possible issues.

@diogoweb2 I'm guessing you were able to make LostGrid work with some wrangling of the build process? If this is a blocker for you (and probably others as well) then we could elevate supporting spaces.

Would you disagree that errors should be a higher priority than supporting spaces?

cc: @codebysubtract

**Comment by steve-holland** [comment]
@peterramsing I think sorting out the error handling is the way forward in the first instance. 

Although I'm not too fussed with the spacing myself either, I guess it would be good to support both styles, then we've covered all eventualities.

**Comment by diogoweb2** [comment]
Hi @peterramsing and @codebysubtract, I agree the priority should be improve the error handling.
I uninstalled the stylefmt plugin and evething works as expected. 

Thanks!
