### ISSUE TITLE
lost in js

### ISSUE THREAD

**Issue by BarryThePenguin** [peterramsing/lost#396]
**Feature Request**

**What is the current behaviour?**

Lost currently needs a preprocessing environment with postcss to work. There is no easy way to use lost without postcss.

**What is the desired behaviour?**

Use [`postcss-js`](https://github.com/postcss/postcss-js) to build the styles for the lost postcss plugin, while also exporting the same functions that allow lost to be used in a css-in-js solution.

**What's the motivation or use-case behind changing the behaviour?**

Using lost in a css-in-js solution like in [`fela`](https://github.com/rofrischmann/fela/) or [`glamor`](https://github.com/threepointone/glamor)

**Comment by corysimmons** [comment]
Lost in React/etc? :o

**Comment by BarryThePenguin** [comment]
That was my thinking!

**Comment by corysimmons** [comment]
@BarryThePenguin Does this break current PostCSS plugin usage?

If not, what comes next? Plugins for all those css-in-js solutions?

>Lost in Next.js via styled-jsx 🤤

**Comment by BarryThePenguin** [comment]
The PR I put together doesn't break current usage, no. It currently looks like an internal refactor to make the internal CSS building part of the `lost` public API.

What comes next is a good question. Plugins for each css-in-js solution would be one way to approach it. A `lost` Github organisation could be an option

**Comment by corysimmons** [comment]
>A lost Github organisation could be an option

@peterramsing ^lol Is it time?

**Comment by peterramsing** [comment]
@corysimmons That's what I keep thinking. ..it's just a real pain to do *but* I really do think it's time.

**Comment by peterramsing** [comment]
@BarryThePenguin I'm very interested in this. In the shower after my run this evening I got all excited about what if there was a core lib that could be used in various places, PostCSS, vanilla JS, etc. The opportunities could be really cool. (As you've already alluded to!)

I also want to get @codebysubtract 's input in on this.

---

I've been really busy at work these past months and I have a few things that I want to get done before moving forward with something like this. It might seem simple but I want to really hammer out what LostGrid is supposed to do on a larger "mission" idea. It's been for PostCSS and I'm a big believer in focus in order to not distract from the core mission/goal. I understand this would still allow for it to be used in PostCSS but I think you're getting my train of thought here. 

---

If @codebysubtract and I'll also lean on @japick and @corysimmons for additional guidance on the core "mission" agree that LostGrid would benefit from this then let's start the next conversation about whether we have a core library that a PostCSS plugin and then maybe this pull in? I don't want to get too complex so maybe that's a bad idea but I want to at least talk about it.

---

Regarding all that "mission" stuff: it's my goal to have done this week. I'm finally taking a holiday from work and hope to use the flights to hammer out my thoughts on the mission, tailboarding, process, etc, for LostGrid so that we can get input and then have more ability to make decisions about this.

**Comment by peterramsing** [comment]
Oh, and anyone else is welcome to comment on the core mission, etc, too! Not just Steve, Jay, and Cory. 😉

**Comment by corysimmons** [comment]
re: Lost's purpose.

I think traditional grids are entering that phase where they start hurting users rather than helping. Flexbox erases the need for all the wrapper/clearfix bloat, and now Grid Layout is going to completely table-flip how we make layouts.

The one thing Grid Layout doesn't offer are misc little helpers for size and such.

postcss-ant approached this problem, but Grid Layout does 90% of what ant does (except for ratios—which I intend to make big).

**All that negative stuff said,** I think Lost doing floats is really helpful for people in China who have gross browsers.

So... I'm not sure. Personally I'd market it as a fallback layout system for people with old browsers.

Within the next year, Grid Layout is going to stomp Lost out. It's up to us to decide if we want to be honest and very clear with people about Lost's purpose.

So far as CSS-in-JS, sure you can wrap Lost up in that stuff, but to add Lost's DSL to markup attributes, especially concerning media queries, the DSL would need to change so significantly it wouldn't really even be Lost anymore. :\

Long ramble short: Lost's mission should be to teach people how to use the best tools for the job. Lost should be where people go when they have no idea how to "layout". Lost should be an org that just focuses on pointing people to the right tools for the job. The grid the org offers should be a fallback grid for old browsers. We should collect tutorials and such in the org. etc. Be good guys.

**Comment by peterramsing** [comment]
@BarryThePenguin, what're your thoughts on what Cory said?

**Comment by BarryThePenguin** [comment]
Hey, thanks all for the input. I think I agree with everything that's been said.

My original thoughts on this was a result of trying to migrate a site away from postcss + lost to a css-in-js solution. My initial approach was to migrate as much css as possible without changing it. That was difficult with the lost syntax, so to keep that I started building `<LostGrid />` elements in react. Which is what created the idea of this issue and the related PR.
