### ISSUE TITLE
Was wondering if lost grid would be upgrading to using css grid

### ISSUE THREAD

**Issue by rlam3** [peterramsing/lost#400]
Was wondering if lost grid would be upgrading to using css grid

https://mozilladevelopers.github.io/playground/

**Comment by corysimmons** [comment]
Personally I think this is a bad idea. Grid Layout is just better unless you're trying to support older browsers.

Grid systems will just convolute a good DSL with their own DSL.

Maybe Lost for generic `@support` fallback, but I don't think upgrading to replicate Grid Layout functionality is 1) a good idea, 2) possible (it's possible, but it'd produce a lot of gross code bloat).

**Comment by rlam3** [comment]
@corysimmons thanks! So moving forward it would be suggested we use css grid?

**Comment by corysimmons** [comment]
Well, I'd wait until there was widespread adoption of CSS Grid, so like, several months to a year?

In the meantime, I think Lost helps out a lot. But yeah, once CSS Grid is here, I'd vote for putting a big notice on the README officially deprecating the project and pointing people directly to the correct stuff.

Pontificating: I think the industry suffers a lot from people holding onto OSS projects and not being 1000% transparent with the past/present/future of their projects.

How many times have any of us used a project because we saw it in a lot of tutorials and such, and it wasn't what we were expecting... like... it was either buggy/incomplete, or just really out-dated.

I think Lost could help set an example for how libs should handle these situations and deprecate with a lot of dignity whenever CSS Grid is super popular.

@peterramsing ^ thoughts?

**Comment by rlam3** [comment]
@corysimmons Thanks... I've started with jeet and then to lost... I guess, I'll have to migrate everything over to css-grid soon. :) Really appreciate your honesty on this matter.

**Comment by corysimmons** [comment]
No problem. Like I said, current grid systems will probably be useful for about another year (until [this](https://caniuse.com/#feat=css-grid) hits 90% global) so I wouldn't hop over just yet (CSS Grid is pretty easy to learn/master over a weekend so no rush).

**Comment by peterramsing** [comment]
@corysimmons, @rlam3,

I do think that LostGrid is ultimately going to be replaced by CSS Grid in many ways. The beauty about LostGrid is that it is lightweight so it can be there in the toolbox of many developers as they migrate to using CSS Grid.

I know most of my work can't move over to CSS grid for quite some time and we're even having to be careful how/where we use Flexbox because of international support–and LostGrid has been a great tool for those cases because it is so compatible.

---
It's a bit odd as OSS isn't a business so I'm not sure how much of a pivot one could do with the underlying architecture to keep it relevant with CSS Grid–but there is an amazing community here and I think that that is where LostGrid will become valuable.

---

Let's be clear, though, LostGrid isn't going by the wayside. Bugs will get fixed Optimizations will happen. I'll be here to help anyone do what they need to do in order to create amazing grids *even* if they aren't using LostGrid. In fact, I'm a huge proponent of **not** using LostGrid when it's not necessary (...even the LostGrid site doesn't use LostGrid...it's not needed and would be added tooling)

**Comment by peterramsing** [comment]
I'll put a note to write up a blog post talking more about this.

---
Going to link to that and close this ticket then.

**Comment by rlam3** [comment]
@peterramsing Would you think a lost-grid to CSS-grid difference / comparison page or tutorial on how to migrate over would be nice for the community in the future? It would probably be very beneficial since most people would likely be looking for a pattern/way to migrate into a new way of using grids. Just curious. Thanks!

**Comment by peterramsing** [comment]
@rlam3, yeah. I'll add that to see if I can either put it in my post and then see where it fits in the docs.

**Comment by corysimmons** [comment]
I actually snagged ~~http://compare.gs~~, [made a site for it](https://github.com/corysimmons/compare.gs/tree/9525782e99d664009b5ff29b81f8e421c0486b9a), etc., to compare all the different grid systems, but felt I'd be judged as a ridiculously biased maintainer of such a project so never filled it in with opinionated data.

I think the site was a tiny bit buggy last I checked.

https://github.com/samccone/grifter/tree/fd3eb9634677834ed050f2eb4231d2c2d4327fb8 looks like a similar concept but probably much better and more performant.

But a grid comparison tool seems like a lot of work to even track down all the grids out there and catalog their features appropriately. I'd be willing to help though if anyone wants to be the primary maintainer.

**Comment by rlam3** [comment]
@corysimmons personally I don't think the lost community needs a grid comparison of all different grid systems but rather a comparison from lost to css-grid for ease of migration. But then again, if the community were to migrate, I'd also think that the whole frontend built on lost would probably scraped and be rewritten in css-grid.... I may be wrong...

**Comment by corysimmons** [comment]
Oh, sorry, I'm half-reading stuff. I'll dip for a bit. :)

**Comment by damien-roche** [comment]
Any suggestions now?

I recently started building a FE with bootstrap grid, then realised CSS Grid support is really good. Started with that, then realised grid-gap and a bunch of other crucial attributes aren't supported in IE (I think Edge is ok). 

I just want a browser compatible grid system. That's it. Never used lost grid but have seen it mentioned a good few times and it looks like exactly what I need. But what is the advice at this point? Jump over to CSS Grid or start with a grid system such as lost?

**Comment by corysimmons** [comment]
@peterramsing I think this is a bad idea. CSS Grid Layout is 👌 and obfuscating it with Lost is 👎 

I think this one can be closed.

**Comment by peterramsing** [comment]
@corysimmons, yeah, I certainly don't want to have LostGrid be a mask for CSS Grid. I mean, *maybe* wrapping a few things, but certainly not attempting to be used in place of CSS Grid where CSS Grid can do all the heavy lifting.

I have thought about offering a way to convert parts of LostGrid to CSS Grid and then have an "eject" process that would remove LostGrid from the picture when browser support is there. That's what I've been doodling on at least.

I do think wrapping CSS Grid with LostGrid for the sake of LostGrid isn't the right idea, though. Offering the ability to convert to CSS Grid with ease from LostGrid would be the goal.

**Comment by peterramsing** [comment]
Alright, to close this issue, I think it would be the wrong move to start adding new things to LostGrid that were to transpile into CSS Grid. I think the best option is to look for ways to allow for a user to "eject" from LostGrid into CSS Grid, or offer documentation on how to move from LostGrid to CSS Grid.

## What about LTS?
LostGrid isn't going away. In fact, I keep hearing more and more people need the legacy support. I just think that it isn't the right move to have users have LostGrid write their CSS Grid.

## CSS Grid & LostGrid?
Yes! Use both! Whether you're transitioning or just love `lost-center` or whatever you might like. Or you have a handle on `@supports` and want to start getting into CSS Grid while maintaining your legacy support, go ahead! If LostGrid gets in the way of CSS Grid please file an issue!

## Is this final?
Nothing is final. If things change then LostGrid might start transpiling things into CSS Grid. But *for now*, I'm not going to actively develop having LostGrid output CSS Grid. **but** I will be actively looking into ways to allow for users to use them side-by-side *and* will be playing with ways a user could "eject" from LostGrid programmatically if they are able to support CSS Grid users only.
