### ISSUE TITLE
lost-align doesn't align correctly.

### ISSUE THREAD

**Issue by ghost** [peterramsing/lost#403]
I just looked at website and saw this. Screenshot below.
**Top**: 115px;
**Bottom**: 85px;

**Is this a feature request or a bug report?**
Bug.

**What is the current behavior?**
Doesn't align correctly.

**If it's a bug please provide the steps to reproduce it and maybe some code samples.**
http://lostgrid.org/lostgrid-example.html

**What version of LostGrid, browser and browser version are affected by this issue? Did this happen in previous versions?**
Chrome on mac.

![screen shot 2018-01-08 at 16 42 52](https://user-images.githubusercontent.com/1254613/34673453-5e42bdb2-f493-11e7-86fc-7d04ddee27f9.png)

**Comment by peterramsing** [comment]
Well, that's awkward. I'll take a look. Thanks.

**Comment by peterramsing** [comment]
Hmm. Something seems up with the translate. I'll keep poking at this.

**Comment by ghost** [comment]
I never get an accurate result with top: 50%. 
It is not surprising to me.

**Comment by peterramsing** [comment]
No, sadly it's not terribly surprising to me either. So what to do what to do? I'm totally enveloped in [Ready Player One](https://en.wikipedia.org/wiki/Ready_Player_One) but once I'm done (super close) I'll see if I can figure out something.

**Comment by ghost** [comment]
Made me laugh. I can't figure why but felt funny.

**Comment by peterramsing** [comment]
Doh! It has everything to do with the margin of the element that is being contained. Because it has the [`margin-top: 15%;`](https://github.com/peterramsing/lost/blob/develop/docs/lostgrid-example.html#L661) added to it it's no longer being centered. I don't think it's actually a problem with `lost-align`. It's a problem with the example, though. I'll fix that. 👍 Thanks for catching that!

**Comment by peterramsing** [comment]
Huzzah! It's fixed. Thanks again @atilkan!
